/**
 * Entity tag taxonomy — the only valid values for entity_tags.tag.
 * Mirrors the canonical list documented in @continuum/db schema/taxonomy.ts.
 */
export const ENTITY_TAGS = [
  "gp_vc",
  "gp_pe",
  "gp_credit",
  "gp_distressed",
  "lp_pension",
  "lp_insurance",
  "lp_dfi",
  "lp_family_office",
  "lp_fof",
  "bank",
  "non_bank_lender",
  "servicer",
  "collection_agency",
  "advisor_ma",
  "placement_agent",
  "law_firm",
  "insolvency_practitioner",
  "accounting",
  "valuer",
  "fund_admin",
  "dd_provider",
  "restructuring_advisor",
  "data_provider",
  "pr_ir",
  "exec_search",
  "regulator",
  "ministry",
  "agency_investment_promotion",
  "state_amc",
  "registry_body",
  "court",
  "stock_exchange",
  "incubator",
  "accelerator",
  "university",
  "association",
  "media",
  "startup",
  "scaleup",
  "sme",
  "corporate",
  "spv",
] as const;

export type EntityTag = (typeof ENTITY_TAGS)[number];
